### ISSUE TITLE
:mget(array_of_key_names, callback) needed

### ISSUE THREAD

**Issue by dvv** [tadeuszwojcik/luvit-redis#3]
Hi!

I would like to mget potentially large amount of keys, how do I do that? Currently, I hit argc limit (250?).

TIA,
--Vladimir

**Comment by twojcik** [comment]
Hi Vladimir :)

I'll take care of fixing it during the weekend as currently 256 args is hardcoded limit in redis.c

```
#define LUA_REDIS_MAX_ARGS (256) 
```

Cheers,
Tadek
