### ISSUE TITLE
Build fails looking for ares.h on luvit 0.7.0

### ISSUE THREAD

**Issue by develephant** [tadeuszwojcik/luvit-redis#7]
git submodule update --init deps/hiredis
Submodule 'deps/hiredis' (git://github.com/redis/hiredis.git) registered for path 'deps/hiredis'
Cloning into 'deps/hiredis'...
remote: Counting objects: 2165, done.
remote: Compressing objects: 100% (958/958), done.
remote: Total 2165 (delta 1288), reused 2012 (delta 1158)
Receiving objects: 100% (2165/2165), 653.51 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1288/1288), done.
Checking connectivity... done.
Submodule path 'deps/hiredis': checked out 'bcf83543762577a9b0f5625c848b7061cc980f30'
make -C deps/hiredis libhiredis.a
make[1]: Entering directory `/root/luvit-redis/deps/hiredis'
cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb  net.c
cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb  hiredis.c
cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb  sds.c
cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb  async.c
ar rcs libhiredis.a net.o hiredis.o sds.o async.o
make[1]: Leaving directory`/root/luvit-redis/deps/hiredis'
mkdir -p build
cc -I/usr/local/include/luvit -I/usr/local/include/luvit/uv -I/usr/local/include/luvit/luajit -I/usr/local/include/luvit/http_parser -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall  -fPIC -Ideps/hiredis -Isrc -o build/redis.luvit src/redis.c deps/hiredis/libhiredis.a -shared -lm deps/hiredis/libhiredis.a
In file included from src/redis.c:26:0:
src/luvit-hiredis-adapter.h:15:5: error: unknown type name 'ev_io'
     ev_io rev, wev;
     ^
src/luvit-hiredis-adapter.h:18:33: error: unknown type name 'EV_P_'
 static void redisLibevReadEvent(EV_P_ ev_io _watcher, int revents) {
                                 ^
src/luvit-hiredis-adapter.h:28:34: error: unknown type name 'EV_P_'
 static void redisLibevWriteEvent(EV_P_ ev_io *watcher, int revents) {
                                  ^
src/luvit-hiredis-adapter.h: In function 'redisLibevAddRead':
src/luvit-hiredis-adapter.h:44:9: warning: implicit declaration of function 'ev_io_start' [-Wimplicit-function-declaration]
         ev_io_start(EV_A_ &e->rev);
         ^
src/luvit-hiredis-adapter.h:44:21: error: 'EV_A_' undeclared (first use in this function)
         ev_io_start(EV_A_ &e->rev);
                     ^
src/luvit-hiredis-adapter.h:44:21: note: each undeclared identifier is reported only once for each function it appears in
src/luvit-hiredis-adapter.h: In function 'redisLibevDelRead':
src/luvit-hiredis-adapter.h:54:9: warning: implicit declaration of function 'ev_io_stop' [-Wimplicit-function-declaration]
         ev_io_stop(EV_A_ &e->rev);
         ^
src/luvit-hiredis-adapter.h:54:20: error: 'EV_A_' undeclared (first use in this function)
         ev_io_stop(EV_A_ &e->rev);
                    ^
src/luvit-hiredis-adapter.h: In function 'redisLibevAddWrite':
src/luvit-hiredis-adapter.h:64:21: error: 'EV_A_' undeclared (first use in this function)
         ev_io_start(EV_A_ &e->wev);
                     ^
src/luvit-hiredis-adapter.h: In function 'redisLibevDelWrite':
src/luvit-hiredis-adapter.h:74:20: error: 'EV_A_' undeclared (first use in this function)
         ev_io_stop(EV_A_ &e->wev);
                    ^
src/luvit-hiredis-adapter.h: At top level:
src/luvit-hiredis-adapter.h:85:29: error: unknown type name 'EV_P_'
 static int redisLibevAttach(EV_P_ redisAsyncContext *ac) {
                             ^
src/redis.c: In function 'lua_create_client':
src/redis.c:359:3: warning: implicit declaration of function 'redisLibevAttach' [-Wimplicit-function-declaration]
   redisLibevAttach(EV_DEFAULT_ redis_async_context);
   ^
src/redis.c:359:20: error: 'EV_DEFAULT_' undeclared (first use in this function)
   redisLibevAttach(EV_DEFAULT_ redis_async_context);
                    ^
src/redis.c:359:32: error: expected ')' before 'redis_async_context'
   redisLibevAttach(EV_DEFAULT_ redis_async_context);
                                ^
In file included from src/redis.c:26:0:
src/redis.c: At top level:
src/luvit-hiredis-adapter.h:38:13: warning: 'redisLibevAddRead' defined but not used [-Wunused-function]
 static void redisLibevAddRead(void *privdata) {
             ^
src/luvit-hiredis-adapter.h:58:13: warning: 'redisLibevAddWrite' defined but not used [-Wunused-function]
 static void redisLibevAddWrite(void *privdata) {
             ^
src/luvit-hiredis-adapter.h:78:13: warning: 'redisLibevCleanup' defined but not used [-Wunused-function]
 static void redisLibevCleanup(void *privdata) {
             ^
make: *_\* [build/redis.luvit] Error 1

**Comment by tadeuszwojcik** [comment]
I'm bit busy right now so looking forward for pull request :smile:  Will try to work this out after new year
